"""Add scored relation between conversations and sources.

Revision ID: 1043f6fd7235
Revises: 45368adac5dc
Create Date: 2024-08-26 14:23:01.144525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1043f6fd7235'
down_revision: Union[str, None] = '45368adac5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
