"""Made the imageUrl optional in the article.

Revision ID: 1296118ad633
Revises: 3568d3ea51e5
Create Date: 2024-09-06 15:15:46.186275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1296118ad633'
down_revision: Union[str, None] = '3568d3ea51e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'imageUrl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'imageUrl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
