"""Added chat conversation

Revision ID: 2867f8c47004
Revises: 6a163b2858cb
Create Date: 2024-08-09 14:04:09.406477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2867f8c47004'
down_revision: Union[str, None] = '6a163b2858cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatconversation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('chatmessage', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chatmessage', 'chatconversation', ['conversation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatmessage', type_='foreignkey')
    op.drop_column('chatmessage', 'conversation_id')
    op.drop_table('chatconversation')
    # ### end Alembic commands ###
