"""Modified settings because conflicting column name.

Revision ID: 2ea76ef9508c
Revises: 9730adcfbe1d
Create Date: 2024-08-28 10:31:30.446787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ea76ef9508c'
down_revision: Union[str, None] = '9730adcfbe1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add new column
    op.add_column('user_settings', sa.Column(
        'ai_provider', sa.String(), nullable=True))

    # Copy data from old column to new column
    op.execute('UPDATE user_settings SET ai_provider = model_provider')

    # Make new column not nullable
    op.alter_column('user_settings', 'ai_provider', nullable=False)

    # Drop old column
    op.drop_column('user_settings', 'model_provider')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('model_provider',
                  sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_settings', 'ai_provider')
    # ### end Alembic commands ###
