"""Added user setting

Revision ID: 4f7ef649c5e3
Revises: 1043f6fd7235
Create Date: 2024-08-28 09:23:04.728849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7ef649c5e3'
down_revision: Union[str, None] = '1043f6fd7235'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('setting_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'user_settings', ['setting_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'setting_id')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
