"""Modified user settings.

Revision ID: 5928b145547a
Revises: 4f7ef649c5e3
Create Date: 2024-08-28 09:39:58.173143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5928b145547a'
down_revision: Union[str, None] = '4f7ef649c5e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('model_provider', sa.String(), nullable=True))
    op.drop_column('user_settings', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_settings', 'model_provider')
    # ### end Alembic commands ###
