"""Added chat message

Revision ID: 6a163b2858cb
Revises: 17421c419b73
Create Date: 2024-08-09 12:39:50.749986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a163b2858cb'
down_revision: Union[str, None] = '17421c419b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatmessage', sa.Column('content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatmessage', 'content')
    # ### end Alembic commands ###
