"""Modified user settings.

Revision ID: 9730adcfbe1d
Revises: 19ab2d22b642
Create Date: 2024-08-28 09:56:59.090102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9730adcfbe1d'
down_revision: Union[str, None] = '19ab2d22b642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'model_provider',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('user_settings', 'user_id',
                    existing_type=sa.UUID(),
                    nullable=False)
    # ### end Alembic commands ###
    op.execute(
        """
        INSERT INTO user_settings (id, model_provider, user_id)
        SELECT gen_random_uuid(), 'mistral', id
        FROM users
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_settings', 'user_id',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('user_settings', 'model_provider',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    # ### end Alembic commands ###
