"""Linked chatconversation to users.

Revision ID: 9a062181b1df
Revises: f8a0df904a35
Create Date: 2024-08-18 09:02:26.227311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a062181b1df'
down_revision: Union[str, None] = 'f8a0df904a35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatconversation', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chatconversation', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatconversation', type_='foreignkey')
    op.drop_column('chatconversation', 'user_id')
    # ### end Alembic commands ###
