"""Modified types declarations

Revision ID: ee021eb854b3
Revises: 2ea76ef9508c
Create Date: 2024-08-29 08:53:05.918391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee021eb854b3'
down_revision: Union[str, None] = '2ea76ef9508c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('articles', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('articles', 'imageUrl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('articles', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('articles', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chatconversation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chatconversation', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('chatmessage', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('chatmessage', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chatmessage', 'type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chatmessage', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversation_context_article', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('conversation_context_article', 'article_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversation_context_article', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversation_context_video', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('conversation_context_video', 'video_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversation_context_video', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('videos', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('videos', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('videos', 'imageUrl',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('videos', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('videos', 'publishDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('videos', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('videos', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('videos', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('videos', 'publishDate',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('videos', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('videos', 'imageUrl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('videos', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('videos', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('conversation_context_video', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversation_context_video', 'video_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversation_context_video', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('conversation_context_article', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversation_context_article', 'article_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversation_context_article', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('chatmessage', 'conversation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chatmessage', 'type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chatmessage', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('chatmessage', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('chatconversation', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('chatconversation', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('articles', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('articles', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('articles', 'imageUrl',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('articles', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('articles', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
